name: Turso Data Migration

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run Turso migration task
        env:
          CLUSTER: GoApiInfraStack-GoApiClusterD2A0AA60-CFXrINUBRSky
          SERVICE: GoApiInfraStack-GoApiFargateService7D208A3F-R1XncDM5OMTl
          TASK_DEFINITION: GoApiInfraStackGoApiFargateServiceTaskDef1BE268E8
          DB_SECRET_ARN: ${{ secrets.DB_SECRET_ARN }}
          TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
          PG_DSN: ${{ secrets.PG_DSN }}
        run: |
          chmod +x ./.github/scripts/run_turso_migration_task.sh
          ./.github/scripts/run_turso_migration_task.sh
